services:
  db:
    image: postgres
    container_name: flask_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: senior-project
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flask-backend:
    build: ./backend
    container_name: flask-backend
    restart: always
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - "5002:5000"
    env_file:
      - ./backend/.env
    command: ["sh", "-c", "flask db upgrade && watchmedo auto-restart --directory=. --pattern=*.py --recursive -- flask run --host=0.0.0.0 --port=5000 --debug"]

  frontend:
    build: ./frontend
    container_name: vite-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    depends_on:
      - flask-backend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
    driver: local
