export const COUNTRIES = [
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Australia', value: 'Australia' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Canada', value: 'Canada' },
  { label: 'China', value: 'China' },
  { label: 'France', value: 'France' },
  { label: 'Germany', value: 'Germany' },
  { label: 'India', value: 'India' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Japan', value: 'Japan' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Russia', value: 'Russia' },
  { label: 'Saudi Arabia', value: 'Saudi Arabia' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Thailand', value: 'Thailand' },
  { label: 'Turkey', value: 'Turkey' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'United States', value: 'United States' },
  { label: 'Other', value: 'Other' },
];

export const PRODUCTS = [
  { label: 'Dental implant', value: 'Dental implant' },
  { label: 'Mandible reconstruction', value: 'Mandible reconstruction' },
  { label: 'Mandible reconstruction with fibula flap', value: 'Mandible reconstruction with fibula flap' },
  { label: 'Maxilla reconstruction', value: 'Maxilla reconstruction' },
  { label: 'Metacarpal implant', value: 'Metacarpal implant' },
  { label: 'Orbital floor reconstruction', value: 'Orbital floor reconstruction' },
  { label: 'Orthognathic surgery', value: 'Orthognathic surgery' },
  { label: 'Pedicle screw (Spine)', value: 'Pedicle screw (Spine)' },
  { label: 'Sacral prosthesis', value: 'Sacral prosthesis' },
  { label: 'Talus', value: 'Talus' },
  { label: 'Virtual Planning', value: 'Virtual Planning' },
];