"""Rename uploaded_at to created_at, add original_filename to case_file_versions

Revision ID: 096153794819
Revises: f80b36be911d
Create Date: 2025-05-09 07:39:01.616493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '096153794819'
down_revision = 'f80b36be911d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_file_versions', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        # batch_op.alter_column('current_version_id',
        #        existing_type=sa.UUID(),
        #        type_=sa.String(),
        #        existing_nullable=True)
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        # batch_op.alter_column('original_version_id',
        #        existing_type=sa.UUID(),
        #        type_=sa.String(),
        #        existing_nullable=False)
        # batch_op.alter_column('resulting_version_id',
        #        existing_type=sa.UUID(),
        #        type_=sa.String(),
        #        nullable=False)
        batch_op.alter_column('is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        # batch_op.alter_column('resulting_version_id',
        #        existing_type=sa.String(),
        #        type_=sa.UUID(),
        #        nullable=True)
        # batch_op.alter_column('original_version_id',
        #        existing_type=sa.String(),
        #        type_=sa.UUID(),
        #        existing_nullable=False)

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        # batch_op.alter_column('current_version_id',
        #        existing_type=sa.String(),
        #        type_=sa.UUID(),
        #        existing_nullable=True)
        batch_op.drop_column('original_filename')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('case_file_versions', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
