"""Add active column to case_surgeons

Revision ID: 21fcfe500e37
Revises: f00b6cfd4bbb
Create Date: 2025-05-01 16:35:59.938660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fcfe500e37'
down_revision = 'f00b6cfd4bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_surgeons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_surgeons', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
