"""Remove case file group

Revision ID: 22673871cf33
Revises: 7a0ee2e68316
Create Date: 2025-05-08 07:17:10.453628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22673871cf33'
down_revision = '7a0ee2e68316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cutting_plane_usages')
    op.drop_table('case_file_group_items')
    op.drop_table('case_file_groups')

    # with op.batch_alter_table('case_files', schema=None) as batch_op:
    #     batch_op.alter_column('current_version_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=True)

    # with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
    #     batch_op.alter_column('version_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
    #     batch_op.alter_column('version_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_files', schema=None) as batch_op:
    #     batch_op.alter_column('current_version_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)


    op.create_table('cutting_plane_usages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cutting_plane_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cutting_plane_id'], ['cutting_planes.id'], name='cutting_plane_usages_cutting_plane_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['case_file_versions.id'], name='cutting_plane_usages_version_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cutting_plane_usages_pkey')
    )
    op.create_table('case_file_group_items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_file_id'], ['case_files.id'], name='case_file_group_items_case_file_id_fkey'),
    sa.ForeignKeyConstraint(['group_id'], ['case_file_groups.id'], name='case_file_group_items_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='case_file_group_items_pkey')
    )
    op.create_table('case_file_groups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='case_file_groups_case_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='case_file_groups_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='case_file_groups_pkey')
    )
    # ### end Alembic commands ###
