"""Initial migration after reset

Revision ID: 42012819d9ce
Revises: 
Create Date: 2025-03-10 15:12:39.444371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42012819d9ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=True))
        batch_op.drop_table_comment(
        existing_comment='original_filename'
    )

    with op.batch_alter_table('tech', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('stl', schema=None) as batch_op:
        batch_op.create_table_comment(
        'original_filename',
        existing_comment=None
    )
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
