"""Add quick_cases table

Revision ID: 52730f8fc992
Revises: a7021743d74e
Create Date: 2025-05-03 16:23:26.516681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52730f8fc992'
down_revision = 'a7021743d74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('other_product', sa.String(length=255), nullable=True),
    sa.Column('anatomy', sa.String(length=255), nullable=False),
    sa.Column('surgery_date', sa.Date(), nullable=False),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_cases')
    # ### end Alembic commands ###
