"""Add pre and post columns to case_files

Revision ID: 6e8bc38e4ebf
Revises: d83dd8a5eeb1
Create Date: 2025-05-18 19:18:18.581603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8bc38e4ebf'
down_revision = 'd83dd8a5eeb1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_constraint('case_files_current_version_id_fkey', type_='foreignkey')
        batch_op.alter_column('current_version_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.add_column(sa.Column('pre', sa.Boolean(), nullable=True, server_default=sa.false()))
        batch_op.add_column(sa.Column('post', sa.Boolean(), nullable=True, server_default=sa.false()))

    op.execute("UPDATE case_files SET pre = FALSE, post = FALSE")

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.alter_column('pre', nullable=False)
        batch_op.alter_column('post', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.alter_column('current_version_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
        batch_op.drop_column('post')
        batch_op.drop_column('pre')

    # ### end Alembic commands ###
