"""Make department nullable in Tech model

Revision ID: 703113d21220
Revises: 7c49400b2b2e
Create Date: 2025-03-03 15:08:30.123992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703113d21220'
down_revision = '7c49400b2b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech', schema=None) as batch_op:
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
