"""Make original_filename not null

Revision ID: 70d1c37d7a0d
Revises: 42012819d9ce
Create Date: 2025-03-10 15:14:15.122776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d1c37d7a0d'
down_revision = '42012819d9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl', schema=None) as batch_op:
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl', schema=None) as batch_op:
        batch_op.alter_column('original_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
