"""Restructure CaseFile and CaseFileVersion models

Revision ID: 7a0ee2e68316
Revises: 11f81e5140bb
Create Date: 2025-05-08 06:54:21.964874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0ee2e68316'
down_revision = '11f81e5140bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('case_file_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False, server_default='unknown'))
        batch_op.alter_column('filename', server_default=None)
        batch_op.add_column(sa.Column('nickname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('filetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.alter_column('active', server_default=None)
        batch_op.drop_column('filesize')
        batch_op.drop_column('nickname')
        batch_op.drop_column('filetype')
        batch_op.drop_column('filepath')
        batch_op.drop_column('filename')

    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        pass

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('filetype', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filesize', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('active')

    with op.batch_alter_table('case_file_versions', schema=None) as batch_op:
        batch_op.drop_column('filesize')
        batch_op.drop_column('filetype')
        batch_op.drop_column('nickname')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
