"""Add original and resulting version ID to CuttingPlane

Revision ID: 7e7c60778da3
Revises: 22673871cf33
Create Date: 2025-05-09 04:11:25.773777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7c60778da3'
down_revision = '22673871cf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_version_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('resulting_version_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint('cutting_planes_version_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'case_file_versions', ['resulting_version_id'], ['id'])
        batch_op.create_foreign_key(None, 'case_file_versions', ['original_version_id'], ['id'])
        batch_op.drop_column('version_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cutting_planes_version_id_fkey', 'case_file_versions', ['version_id'], ['id'])
        batch_op.drop_column('resulting_version_id')
        batch_op.drop_column('original_version_id')

    # ### end Alembic commands ###
