"""added profile pic column for user table

Revision ID: 8dadd505b7ec
Revises: 11c5f50a1ab0
Create Date: 2025-04-30 14:58:11.921392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dadd505b7ec'
down_revision = '11c5f50a1ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'profile_pic_files', ['profile_image'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
