"""add cutting_plane_usages table

Revision ID: a37a62e30bf0
Revises: b43d9b8a1175
Create Date: 2025-05-06 19:33:00.144190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37a62e30bf0'
down_revision = 'b43d9b8a1175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutting_plane_usages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cutting_plane_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cutting_plane_id'], ['cutting_planes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['case_file_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('case_file_group_items', schema=None) as batch_op:
    #     batch_op.alter_column('group_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    #     batch_op.alter_column('case_file_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_file_groups', schema=None) as batch_op:
    #     batch_op.alter_column('case_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    #     batch_op.alter_column('created_by',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=True)

    # with op.batch_alter_table('case_file_versions', schema=None) as batch_op:
    #     batch_op.alter_column('case_file_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_files', schema=None) as batch_op:
    #     batch_op.alter_column('current_version_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=True)

    # with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
    #     batch_op.alter_column('version_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
    #     batch_op.alter_column('version_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_files', schema=None) as batch_op:
    #     batch_op.alter_column('current_version_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)

    # with op.batch_alter_table('case_file_versions', schema=None) as batch_op:
    #     batch_op.alter_column('case_file_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_file_groups', schema=None) as batch_op:
    #     batch_op.alter_column('created_by',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    #     batch_op.alter_column('case_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_file_group_items', schema=None) as batch_op:
    #     batch_op.alter_column('case_file_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)
    #     batch_op.alter_column('group_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)

    op.drop_table('cutting_plane_usages')
    # ### end Alembic commands ###
