"""Add case_code and other fields to Case

Revision ID: a7021743d74e
Revises: 21fcfe500e37
Create Date: 2025-05-02 14:33:11.208087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7021743d74e'
down_revision = '21fcfe500e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('product', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('anticipated_ship_date', sa.Date(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('anticipated_ship_date')
        batch_op.drop_column('product')
        batch_op.drop_column('created_by')
        batch_op.drop_column('priority')
        batch_op.drop_column('status')
        batch_op.drop_column('case_code')

    # ### end Alembic commands ###
