"""create cutting_planes table

Revision ID: b43d9b8a1175
Revises: e14566cb07cd
Create Date: 2025-05-06 12:09:35.312613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43d9b8a1175'
down_revision = 'e14566cb07cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cutting_planes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=False),
    sa.Column('normal', sa.JSON(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['case_file_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('case_file_group_items', schema=None) as batch_op:
    #     batch_op.alter_column('group_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    #     batch_op.alter_column('case_file_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_file_groups', schema=None) as batch_op:
    #     batch_op.alter_column('case_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)
    #     batch_op.alter_column('created_by',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=True)

    # with op.batch_alter_table('case_file_versions', schema=None) as batch_op:
    #     batch_op.alter_column('case_file_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_files', schema=None) as batch_op:
    #     batch_op.alter_column('current_version_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('case_files', schema=None) as batch_op:
    #     batch_op.alter_column('current_version_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)

    # with op.batch_alter_table('case_file_versions', schema=None) as batch_op:
    #     batch_op.alter_column('case_file_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)

    # with op.batch_alter_table('case_file_groups', schema=None) as batch_op:
    #     batch_op.alter_column('created_by',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    #     batch_op.alter_column('case_id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False)

    with op.batch_alter_table('case_file_group_items', schema=None) as batch_op:
        batch_op.alter_column('case_file_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)

    op.drop_table('cutting_planes')
    # ### end Alembic commands ###
