"""Change current_version_id to UUID

Revision ID: b49d9edc00cd
Revises: 6e8bc38e4ebf
Create Date: 2025-05-18 22:01:58.774196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49d9edc00cd'
down_revision = '6e8bc38e4ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.alter_column('current_version_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='current_version_id::uuid')
        batch_op.create_foreign_key(None, 'case_file_versions', ['current_version_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('current_version_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
