"""Add quick_case_files table

Revision ID: bf6d5eaa4dd0
Revises: 52730f8fc992
Create Date: 2025-05-03 18:05:55.297828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6d5eaa4dd0'
down_revision = '52730f8fc992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_case_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quick_case_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('filetype', sa.String(length=100), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quick_case_id'], ['quick_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_case_files')
    # ### end Alembic commands ###
