"""edit case file model structure

Revision ID: c0b43fda9dbb
Revises: feacb47e0956
Create Date: 2025-05-05 17:01:12.679310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0b43fda9dbb'
down_revision = 'feacb47e0956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('filetype', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('filesize', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('original_filename')

    op.alter_column('case_files', 'uploaded_at', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('filepath',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('filesize')
        batch_op.drop_column('filetype')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
