"""Make resulting_version_id non-nullable

Revision ID: d83dd8a5eeb1
Revises: 096153794819
Create Date: 2025-05-09 07:42:14.929894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83dd8a5eeb1'
down_revision = '096153794819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        batch_op.alter_column('resulting_version_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        batch_op.alter_column('resulting_version_id', nullable=True)

    # ### end Alembic commands ###
