"""Add case_number to Case model

Revision ID: f00b6cfd4bbb
Revises: dfaf75917bc8
Create Date: 2025-05-01 15:19:42.270676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f00b6cfd4bbb'
down_revision = 'dfaf75917bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('case_number', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.create_unique_constraint(None, ['case_number'])

    op.execute("CREATE TYPE roleenum AS ENUM ('admin', 'doctor', 'technician')")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
                              existing_type=postgresql.ENUM(
                                  'admin', 'doctor', 'technician', name='role'),
                              type_=sa.Enum('admin', 'doctor',
                                            'technician', name='roleenum'),
                              existing_nullable=True,
                              postgresql_using="role::text::roleenum")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
                              existing_type=sa.Enum(
                                  'admin', 'doctor', 'technician', name='roleenum'),
                              type_=postgresql.ENUM(
                                  'admin', 'doctor', 'technician', name='role'),
                              existing_nullable=True)

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('case_number')
    op.execute("DROP TYPE roleenum")

    # ### end Alembic commands ###
