"""Enable cascading deletes for CuttingPlane version refs

Revision ID: f80b36be911d
Revises: 7e7c60778da3
Create Date: 2025-05-09 05:01:54.275634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80b36be911d'
down_revision = '7e7c60778da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        # batch_op.alter_column('original_version_id',
        #        existing_type=sa.UUID(),
        #        type_=sa.String(),
        #        existing_nullable=False)
        # batch_op.alter_column('resulting_version_id',
        #        existing_type=sa.UUID(),
        #        type_=sa.String(),
        #        existing_nullable=True)
        batch_op.drop_constraint('cutting_planes_resulting_version_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cutting_planes_original_version_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'case_file_versions', ['original_version_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'case_file_versions', ['resulting_version_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cutting_planes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cutting_planes_original_version_id_fkey', 'case_file_versions', ['original_version_id'], ['id'])
        batch_op.create_foreign_key('cutting_planes_resulting_version_id_fkey', 'case_file_versions', ['resulting_version_id'], ['id'])
        # batch_op.alter_column('resulting_version_id',
        #        existing_type=sa.String(),
        #        type_=sa.UUID(),
        #        existing_nullable=True)
        # batch_op.alter_column('original_version_id',
        #        existing_type=sa.String(),
        #        type_=sa.UUID(),
        #        existing_nullable=False)

    # ### end Alembic commands ###
