"""add case_technician model and case relationships

Revision ID: f89bd70f22b6
Revises: ddb84e132416
Create Date: 2025-05-04 15:27:27.140799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89bd70f22b6'
down_revision = 'ddb84e132416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_technicians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_surgeons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('case_surgeons_surgeon_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('case_surgeons_case_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctors', ['surgeon_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'cases', ['case_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_registration_id', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('doctors_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_constraint('technicians_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('technicians_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('doctors_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('doctor_registration_id')

    with op.batch_alter_table('case_surgeons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('case_surgeons_case_id_fkey', 'cases', ['case_id'], ['id'])
        batch_op.create_foreign_key('case_surgeons_surgeon_id_fkey', 'doctors', ['surgeon_id'], ['id'])
        batch_op.drop_column('updated_at')

    op.drop_table('case_technicians')
    # ### end Alembic commands ###
