"""Use timezone-aware timestamps in STL model

Revision ID: f90d16544897
Revises: 70d1c37d7a0d
Create Date: 2025-03-18 11:04:58.724092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90d16544897'
down_revision = '70d1c37d7a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stl', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
