"""add reference field to Doctor model

Revision ID: feacb47e0956
Revises: f89bd70f22b6
Create Date: 2025-05-04 17:29:18.146365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feacb47e0956'
down_revision = 'f89bd70f22b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
